version: '3'
services:
  webapp:
    container_name: webapp
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "mydb"
    command: ["./wait-for-it.sh" , "mydb:3306" , "--strict" , "--timeout=60" , "--" , "./django_migrate_and_runserver.sh"]

  mydb:
    container_name: mydb
    image: plaulkar/mysql_custom
    ports:
      - "3302:3306" 