kind: Service
apiVersion: v1
metadata:
  name: mongoexpress-service 
spec:
  selector:
    app: mongo-express 
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
  type: NodePort

