version: '3'
services:
  webapp:
    image: mysqldjango_webapp
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "mydb"
    command: ["./wait-for-it.sh" , "mydb:3306" , "--strict" , "--timeout=30" , "--" , "./django_migrate_and_runserver.sh"]

  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: '7htdv3eh5t'
      MYSQL_DATABASE: 'mysql'
    expose:
      - "3306"
    ports:
      - "3302:3306"
