apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache       
  labels:          
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache                                                                                      
    spec:                                                                                   
      containers:
      - name: apache
        image: plaulkar/alpine-with-apache:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"