apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:          
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db                                                                                     
    spec:                                                                                   
      containers:
      - name: mysql-db
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: MYSQL_ROOT_PASSWORD