apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp       
  labels:      
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:                           
      containers:
      - name: webapp
        image: plaulkar/default_django_app_mysql_db:alpine
        ports:
        - containerPort: 8000
