apiVersion: v1
kind: Pod
metadata:
  labels:
    run: volume-share-datacenter
  name: volume-share-datacenter
spec:
  volumes:
  - name: volume-share
    emptyDir: {}
  containers:
  - command:
    - sleep
    - "1000"
    image: fedora:latest
    name: volume-container-datacenter-1
    volumeMounts:
      - name: volume-share
        mountPath: /tmp/official
  - command:
    - sleep
    - "1000"
    image: fedora:latest
    name: volume-container-datacenter-2
    volumeMounts:
      - name: volume-share
        mountPath: /tmp/cluster